#!/bin/bash
#SBATCH --partition=nanosim
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --time=48:00:00
#SBATCH --mem=14000mb
#SBATCH --job-name=ox_distort_clusters

export OMP_NUM_THREADS=32
[ ! -z "$SLURM_ARRAY_TASK_ID" ] && export LOGSUFFIX="_"$SLURM_ARRAY_TASK_ID
python ../oxirane.py clusters ox distort | tee -a orca/ox_distort_clusters$LOGSUFFIX.log
