#!/bin/bash
#SBATCH --partition=nanosimd
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=128
#SBATCH --time=48:00:00
#SBATCH --mem=14000mb
#SBATCH --job-name=ox_es1_MACEac7u_U_clusters

export OMP_NUM_THREADS=128
[ ! -z "$SLURM_ARRAY_TASK_ID" ] && export LOGSUFFIX="_"$SLURM_ARRAY_TASK_ID
python ../oxirane.py clusters ox es1_MACEac7u_U | tee -a orca_ac7u/ox_es1_MACEac7u_U_clusters$LOGSUFFIX.log
