#!/bin/bash
#SBATCH --partition=nanosimd
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=1
#SBATCH --time=48:00:00
#SBATCH --mem=14000mb
#SBATCH --job-name=ox_md300_solvate

export OMP_NUM_THREADS=1
[ ! -z "$SLURM_ARRAY_TASK_ID" ] && export LOGSUFFIX="_"$SLURM_ARRAY_TASK_ID
python ../oxirane.py solvate ox md300 | tee -a ox_md300_solvate$LOGSUFFIX.log
