#!/bin/bash
#SBATCH --partition=nanosimd
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=48:00:00
#SBATCH --mem=14000mb
#SBATCH --job-name=ox_orca_qmd

export OMP_NUM_THREADS=8
[ ! -z "$SLURM_ARRAY_TASK_ID" ] && export LOGSUFFIX="_"$SLURM_ARRAY_TASK_ID
python ../oxirane.py qmd ox orca | tee -a ox_orca_qmd$LOGSUFFIX.log
